jest.setTimeout(60000);
process.env.NODE_ENV = 'test';
process.env.POSTGRES_HOST = 'localhost';
process.env.POSTGRES_DB = 'kruger-test';
process.env.POSTGRES_USER = 'postgres';
process.env.POSTGRES_PASSWORD = 'postgres';
process.env.PORT = '4001';
process.env.REDIS_URL = '127.0.0.1:6379';
process.env.SESSION_SECRET = 'testing_secret';
process.env.CORS_ORIGIN = 'http://localhost:3000';
