name: Run CI
on:
    push:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "server"
        steps:
            - name: Check Out Repo
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kyker-server:latest

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
